# Generated by Django 5.1.3 on 2024-11-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='adresse',
            field=models.CharField(default='Non spécifié', max_length=255),
        ),
    ]
