# Generated by Django 5.1.3 on 2024-11-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membre',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='list_Medias/'),
        ),
    ]
