# Generated by Django 5.1.3 on 2024-11-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
